# .github/workflows/ci.yml

name: Backend CI

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master", "develop" ]
    paths:
      - 'backend/**'
      - '.github/workflows/ci.yml' # Also run on workflow changes
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        source $HOME/.cargo/env
        uv --version

    - name: Install dependencies
      run: uv pip install -r requirements.txt --system

    # --- NEW DEBUGGING STEP ---
    - name: Verify Installation & Environment
      run: |
        echo "--- Python Path ---"
        which python
        echo "--- Installed Packages (pip list) ---"
        python -m pip list
        echo "--- Installed Packages (uv pip list) ---"
        uv pip list --system

    - name: Run tests with pytest
      working-directory: ./backend
      run: |
        echo "--- Running tests from directory: $(pwd) ---"
        python -m pytest