
name: Backend CI

on:
  push:
    branches: [ "main", "master", "develop" ] 
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Install dependencies
      run: |
        source $HOME/.cargo/env
        uv pip install -r requirements.txt
        # uv pip install fastapi uvicorn sqlalchemy pydantic slowapi pytest httpx

    - name: Run tests with pytest
      working-directory: ./backend # Run tests from the backend directory
      run: pytest